name: Run action on different operating systems
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            energyplus-version: '22.1.0'
            energyplus-sha: 'ed759b17ee'
          - os: ubuntu-latest
            energyplus-version: '24.2.0'
            energyplus-sha: '94a887817b'
            energyplus-tag: 'v24.2.0a'
            energyplus-platform: 'Linux-Ubuntu24.04'
            energyplus-arch: 'x86_64'
          - os: macos-latest
            energyplus-version: '22.1.0'
            energyplus-sha: 'ed759b17ee'
          - os: windows-latest
            energyplus-version: '22.1.0'
            energyplus-sha: 'ed759b17ee'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run private action
      uses: ./
      with:
          energyplus-version: ${{ matrix.energyplus-version }}
          energyplus-sha: ${{ matrix.energyplus-sha }}
          energyplus-tag: ${{ matrix.energyplus-tag }}
          energyplus-platform: ${{ matrix.energyplus-platform }}
          energyplus-arch: ${{ matrix.energyplus-arch }}
    - name: Display installed version
      shell: bash
      run: |
        set -e
        echo "Installed EnergyPlusVersion $(energyplus --version)"
